version: "3.3"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_SERVER=redis
  redis:
    image: "swapsstyle/anthos-backend:v1"
    ports:
      - "6379:6379"